from __future__ import annotations

import hashlib
import io
import json
import zipfile

from PIL import Image

from image23mf.calibration import (
    ATTESTATION_STATEMENT,
    CalibrationAttestation,
    CalibrationEvidenceManifest,
    CalibrationEvidenceMember,
    CalibrationEvidenceRole,
    CalibrationFilamentEvidence,
    CalibrationPinnedProfileEvidence,
    CalibrationRunRecord,
    CalibrationSlicerEvidence,
    build_calibration_evidence_bundle,
    generate_calibration_artifact,
    load_bundled_printability_catalog,
)


def complete_evidence_bundle(
    *,
    run_id: str = "calibration-run-p2s-04-physical-0001",
    observation_mode: str = "mixed",
    layer_height_mm: float = 0.2,
) -> tuple[bytes, CalibrationEvidenceManifest]:
    catalog = load_bundled_printability_catalog()
    profile = next(item for item in catalog.profiles if item.nozzle_diameter_mm == 0.4)
    artifact = generate_calibration_artifact(profile, raster_mm_per_pixel=0.07)
    record_payload = artifact.record_template.model_dump(mode="json")
    record_payload.update(
        {
            "status": "completed",
            "record_id": run_id,
            "layer_height_mm": layer_height_mm,
            "plate_id": "textured-pei",
            "filament": "Bambu PLA Basic Black",
            "operator": "Kelly",
            "printed_on": "2026-07-17",
            "slicer_profile": "0.20mm Standard @BBL P2S",
        }
    )
    feature_by_id = {item.id: item for item in artifact.manifest.features}
    observations = []
    for index, observation in enumerate(record_payload["observations"]):
        feature = feature_by_id[observation["feature_id"]]
        if observation_mode == "uncertain-dot" and feature.kind.value == "dot":
            outcome = (
                "uncertain" if feature.column == 1 else "fail" if feature.column == 0 else "pass"
            )
            measured = 0 if feature.column == 0 else None
        elif observation_mode == "nonmonotonic-dot" and feature.kind.value == "dot":
            outcome = "fail" if feature.column == 1 else "pass"
            measured = feature.rasterized_dimension_mm
        elif observation_mode in {"monotonic", "uncertain-dot", "nonmonotonic-dot"}:
            outcome = "fail" if feature.column < 2 else "pass"
            measured = 0 if feature.column == 0 else feature.rasterized_dimension_mm
        else:
            outcome = "fail" if index == 0 else "uncertain" if index == 1 else "pass"
            measured = 0 if index == 0 else None
        observations.append(
            {
                **observation,
                "outcome": outcome,
                "measured_dimension_mm": measured,
            }
        )
    record_payload["observations"] = observations
    record = CalibrationRunRecord.model_validate(record_payload)

    filament_payload = {
        "filament_id": "bambu-pla-basic-black",
        "manufacturer": "Bambu Lab",
        "family": "Basic",
        "name": "Bambu PLA Basic Black",
        "material": "PLA",
        "finish": "basic",
        "color_hex": "#000000",
    }
    filament_payload["snapshot_sha256"] = _fingerprint(filament_payload)
    filament = CalibrationFilamentEvidence.model_validate(filament_payload)

    payloads = {
        "payload/coupon.svg": artifact.svg_bytes,
        "payload/coupon.png": artifact.png_bytes,
        "payload/project.3mf": _tiny_3mf(),
        "payload/sliced.gcode": b"; generated by test slicer\nG28\nM84\n",
        "payload/slicer-settings.json": json.dumps(
            {"layer_height": layer_height_mm, "plate": "textured-pei"}, sort_keys=True
        ).encode("utf-8"),
        "payload/photo.png": _tiny_png(),
    }
    definitions = (
        (CalibrationEvidenceRole.COUPON_SVG, 0, "payload/coupon.svg", "image/svg+xml"),
        (CalibrationEvidenceRole.COUPON_PNG, 0, "payload/coupon.png", "image/png"),
        (CalibrationEvidenceRole.PROJECT_3MF, 0, "payload/project.3mf", "model/3mf"),
        (
            CalibrationEvidenceRole.SLICED_GCODE,
            0,
            "payload/sliced.gcode",
            "text/x-gcode",
        ),
        (
            CalibrationEvidenceRole.SLICER_SETTINGS,
            0,
            "payload/slicer-settings.json",
            "application/json",
        ),
        (CalibrationEvidenceRole.PHOTO, 0, "payload/photo.png", "image/png"),
    )
    members = tuple(
        sorted(
            (
                CalibrationEvidenceMember(
                    role=role,
                    ordinal=ordinal,
                    archive_path=path,
                    filename=path.removeprefix("payload/"),
                    sha256=hashlib.sha256(payloads[path]).hexdigest(),
                    byte_size=len(payloads[path]),
                    media_type=media_type,
                    extension="." + path.rsplit(".", 1)[-1],
                )
                for role, ordinal, path, media_type in definitions
            ),
            key=lambda item: (item.role.value, item.ordinal),
        )
    )
    pinned = tuple(
        CalibrationPinnedProfileEvidence(role=role, name=name, sha256=_sha(name))
        for role, name in (
            ("filament", "Bambu PLA Basic Black"),
            ("machine", "Bambu Lab P2S 0.4 nozzle"),
            ("process", "0.20mm Standard @BBL P2S"),
        )
    )
    manifest = CalibrationEvidenceManifest(
        catalog_id=catalog.catalog_id,
        catalog_version=catalog.catalog_version,
        catalog_fingerprint=catalog.fingerprint(),
        profile=profile,
        artifact=artifact.manifest,
        record=record,
        slicer=CalibrationSlicerEvidence(
            application="Bambu Studio",
            version="2.3.0.70",
            executable_sha256=_sha("bambu-studio-2.3.0.70"),
            profiles=pinned,
        ),
        filaments=(filament,),
        attestation=CalibrationAttestation(
            operator="Kelly",
            attested_at="2026-07-17T10:00:00Z",
            statement=ATTESTATION_STATEMENT,
        ),
        members=members,
    )
    return build_calibration_evidence_bundle(manifest, payloads), manifest


def _fingerprint(payload: dict) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def _sha(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _tiny_3mf() -> bytes:
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "[Content_Types].xml",
            '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"/>',
        )
        archive.writestr(
            "3D/3dmodel.model",
            '<?xml version="1.0"?><model unit="millimeter" '
            'xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"/>',
        )
    return output.getvalue()


def _tiny_png() -> bytes:
    output = io.BytesIO()
    with Image.new("RGB", (2, 2), "white") as image:
        image.save(output, format="PNG")
    return output.getvalue()
