import hashlib
import json
import os
import threading
import time
import zipfile
from pathlib import Path

import pytest

from image23mf.bambu.cli import (
    BambuSliceProfiles,
    BambuStudioCanceledError,
    BambuStudioCliValidator,
    BambuStudioProfileError,
    BambuStudioSliceError,
    BambuStudioTimeoutError,
    BambuStudioUnavailableError,
    BambuValidationStatus,
    InvalidSlicedArtifactError,
    PinnedBambuProfile,
)
from image23mf.bambu.package import Material, Mesh, write_bambu_3mf
from image23mf.bambu.report import SlicerValidationExpectation
from image23mf.external import CancellationToken, ToolRunner
from image23mf.external.registry import ExternalToolRegistry, ToolId, ToolSpec


def fake_bambu(tmp_path: Path, name: str, action: str) -> Path:
    executable = tmp_path / name
    executable.write_text(
        """#!/usr/bin/env python3
import sys
import time
import zipfile
from pathlib import Path

if "--version" in sys.argv:
    with Path(__file__).with_suffix(".version-probes").open("a", encoding="utf-8") as marker:
        marker.write("probe\\n")
    print("BambuStudio-2.7.1.50")
    raise SystemExit(1)

arguments = sys.argv[1:]
output_directory = Path(arguments[arguments.index("--outputdir") + 1])
output_name = arguments[arguments.index("--export-3mf") + 1]
output_path = output_directory / output_name

ACTION
""".replace("ACTION", action),
        encoding="utf-8",
    )
    executable.chmod(0o755)
    return executable


VALID_SLICE = r"""
with zipfile.ZipFile(output_path, "w") as archive:
    archive.writestr(
        "Metadata/plate_1.gcode",
        "; generated by BambuStudio\nG90\nM83\nG1 X1.0 Y2.0 E0.125\n",
    )
print("slice complete")
print("diagnostic stderr", file=sys.stderr)
"""


def validator(tmp_path: Path, executable: Path, *, timeout: float = 2) -> BambuStudioCliValidator:
    runner = ToolRunner(temp_root=tmp_path / "runs")
    spec = ToolSpec(
        id=ToolId.BAMBU_STUDIO,
        name="Bambu Studio",
        purpose="3MF slice validation",
        candidates=(str(executable),),
        version_arguments=("--version",),
        version_pattern=r"BambuStudio-(\d+(?:\.\d+)+)",
        minimum_version=(2, 0),
        allow_nonzero_version_probe=True,
    )
    registry = ExternalToolRegistry(
        runner=runner,
        specs={ToolId.BAMBU_STUDIO: spec},
        # Process launch can briefly exceed one second on a busy macOS host during the
        # complete suite; the fake probe itself returns immediately once scheduled.
        version_timeout_seconds=3,
    )
    return BambuStudioCliValidator(
        runner=runner,
        registry=registry,
        timeout_seconds=timeout,
    )


def source(tmp_path: Path, payload: bytes = b"project", *, extruders: int = 1) -> Path:
    path = tmp_path / "source project;$(unsafe).3mf"
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr(
            "Metadata/project_settings.config",
            '{"filament_settings_id":['
            + ",".join(f'"filament-{index}"' for index in range(extruders))
            + "]}",
        )
        archive.writestr("Metadata/source-proof.bin", payload)
    return path


def pinned_profiles(
    tmp_path: Path,
    *,
    filaments: int = 1,
    prefix: str = "profile;$(safe)",
) -> BambuSliceProfiles:
    profile_directory = tmp_path / prefix
    profile_directory.mkdir(exist_ok=True)
    machine = profile_directory / "machine profile.json"
    process = profile_directory / "process profile.json"
    machine.write_text('{"type":"machine"}', encoding="utf-8")
    process.write_text('{"type":"process"}', encoding="utf-8")
    filament_paths = []
    for index in range(1, filaments + 1):
        path = profile_directory / f"filament {index}.json"
        path.write_text(f'{{"type":"filament","index":{index}}}', encoding="utf-8")
        filament_paths.append(path)
    return BambuSliceProfiles(
        machine=PinnedBambuProfile.pin(machine),
        process=PinnedBambuProfile.pin(process),
        filaments=tuple(PinnedBambuProfile.pin(path) for path in filament_paths),
    )


def test_success_uses_safe_argument_array_and_retains_slice_evidence(tmp_path) -> None:
    marker = tmp_path / "unsafe"
    executable = fake_bambu(tmp_path, "Bambu Studio fake", VALID_SLICE)
    project = source(tmp_path)
    profiles = pinned_profiles(tmp_path)

    result = validator(tmp_path, executable).validate(project, profiles=profiles)

    assert result.status == BambuValidationStatus.VALIDATED
    assert result.executable == executable.resolve()
    assert result.version == "2.7.1.50"
    assert result.return_code == 0
    assert result.stdout == "slice complete\n"
    assert result.stderr == "diagnostic stderr\n"
    assert not result.timed_out
    assert not result.canceled
    assert result.warnings == ()
    source_sha256 = hashlib.sha256(project.read_bytes()).hexdigest()
    assert result.source_sha256 == source_sha256
    assert result.command[0] == str(executable.resolve())
    assert result.command[1] == "--load-settings"
    assert result.command[3] == "--load-filaments"
    assert "--no-check" in result.command
    arrange_index = result.command.index("--arrange")
    assert result.command[arrange_index : arrange_index + 2] == ("--arrange", "0")
    slice_index = result.command.index("--slice")
    assert arrange_index < slice_index
    assert result.command[slice_index : slice_index + 4] == ("--slice", "0", "--debug", "2")
    assert result.command[2].count(";") == 1
    assert ";$(safe)" not in result.command[2]
    assert ";$(safe)" not in result.command[4]
    assert result.command[-1].endswith(f"input-{source_sha256[:24]}.3mf")
    assert "source project;$(unsafe).3mf" not in result.command
    assert not marker.exists()
    assert result.artifact is not None
    assert result.artifact.name.endswith(".gcode.3mf")
    assert result.artifact.gcode_members == ("Metadata/plate_1.gcode",)
    assert result.artifact.uncompressed_gcode_bytes > 0
    assert len(result.artifact.plates) == 1
    assert result.artifact.plates[0].has_extrusion is True
    assert result.report is not None
    assert result.report.raw_logs.stdout == "slice complete\n"
    assert result.report.raw_logs.stderr == "diagnostic stderr\n"
    assert len(result.artifact.sha256) == 64
    assert [item.role for item in result.profiles] == ["machine", "process", "filament"]
    assert all(item.expected_sha256 == item.actual_sha256 for item in result.profiles)
    assert result.profile_set_sha256 is not None
    assert len(result.profile_set_sha256) == 64
    assert result.cache_key is not None
    assert result.cache_key.startswith("image23mf-bambu-cli-validation-v3:")
    assert list((tmp_path / "runs").iterdir()) == []


def test_success_preserves_warnings_without_downgrading_valid_artifact(tmp_path) -> None:
    action = VALID_SLICE + '\nprint("warning: repaired tiny gap", file=sys.stderr)\n'
    executable = fake_bambu(tmp_path, "warn", action)

    result = validator(tmp_path, executable).validate(
        source(tmp_path), profiles=pinned_profiles(tmp_path)
    )

    assert result.status == BambuValidationStatus.VALIDATED
    assert result.warnings == ("warning: repaired tiny gap",)
    assert "warning: repaired tiny gap" in result.stderr


def test_mural_tower_settings_override_loaded_process_profile_for_every_plate(tmp_path) -> None:
    action = (
        r"""
import json
process_path = Path(arguments[arguments.index("--load-settings") + 1].split(";")[1])
process = json.loads(process_path.read_text(encoding="utf-8"))
assert process["enable_prime_tower"] == "1"
assert process["prime_tower_width"] == "35.0"
assert process["wipe_tower_x"] == ["208.0"] * 6
assert process["wipe_tower_y"] == ["208.0"] * 6
"""
        + VALID_SLICE
    )
    executable = fake_bambu(tmp_path, "mural-process-overlay", action)
    project = source(tmp_path)
    with zipfile.ZipFile(project, "a") as archive:
        archive.writestr(
            "Metadata/image23mf_mural.json",
            json.dumps(
                {
                    "prime_tower": {
                        "policy": "enabled_slicer_generated_tower",
                        "inserted_geometry": False,
                        "x_mm": 205,
                        "y_mm": 205,
                        "tower_x_mm": 208,
                        "tower_y_mm": 208,
                        "tower_width_mm": 35,
                    },
                    "plates": [{"build_plate_index": index} for index in range(1, 7)],
                }
            ),
        )
    profiles = pinned_profiles(tmp_path)

    result = validator(tmp_path, executable).validate(project, profiles=profiles)

    assert result.status == BambuValidationStatus.VALIDATED
    assert json.loads(profiles.process.path.read_text(encoding="utf-8")) == {"type": "process"}


def test_expected_colors_are_enforced_against_used_slicer_filaments(tmp_path) -> None:
    action = r"""
with zipfile.ZipFile(output_path, "w") as archive:
    archive.writestr(
        "Metadata/plate_1.gcode",
        "; HEADER_BLOCK_START\n"
        "; total layer number: 1\n"
        "; total filament length [mm] : 10\n"
        "; total filament volume [cm^3] : 24.05\n"
        "; total filament weight [g] : 0.03\n"
        "; max_z_height: 0.2\n"
        "; filament: 1\n"
        "; HEADER_BLOCK_END\n"
        "; CONFIG_BLOCK_START\n"
        "; filament_colour = #CBC6B8;#F99963\n"
        "; CONFIG_BLOCK_END\n"
        "M83\n; CHANGE_LAYER\n; Z_HEIGHT: 0.2\nG1 X1 Y2 E0.1\n",
    )
"""
    executable = fake_bambu(tmp_path, "color-proof", action)

    with pytest.raises(InvalidSlicedArtifactError, match="missing expected colors") as raised:
        validator(tmp_path, executable).validate(
            source(tmp_path),
            profiles=pinned_profiles(tmp_path),
            expectation=SlicerValidationExpectation(expected_colors=("#CBC6B8", "#F99963")),
        )

    assert raised.value.result.artifact is not None
    assert raised.value.result.report is not None
    assert raised.value.result.report.observed_colors == ("#CBC6B8",)
    assert raised.value.result.report.missing_expected_colors == ("#F99963",)
    command = raised.value.result.command
    color_argument = command[command.index("--filament-colour") + 1]
    assert color_argument == "#CBC6B8;#F99963"
    assert command.index("--filament-colour") < command.index("--no-check")


def test_nonzero_exit_retains_version_logs_exit_and_no_false_artifact(tmp_path) -> None:
    executable = fake_bambu(
        tmp_path,
        "failure",
        'print("could not slice"); print("invalid profile", file=sys.stderr); raise SystemExit(23)',
    )

    with pytest.raises(BambuStudioSliceError) as raised:
        validator(tmp_path, executable).validate(
            source(tmp_path), profiles=pinned_profiles(tmp_path)
        )

    result = raised.value.result
    assert result.status == BambuValidationStatus.FAILED
    assert result.executable == executable.resolve()
    assert result.version == "2.7.1.50"
    assert result.return_code == 23
    assert result.stdout == "could not slice\n"
    assert result.stderr == "invalid profile\n"
    assert result.artifact is None


@pytest.mark.parametrize(
    ("action", "message"),
    [
        (
            'with zipfile.ZipFile(output_path, "w") as archive:\n'
            '    archive.writestr("Metadata/readme.txt", "not G-code")',
            "no plate G-code artifact",
        ),
        (
            'with zipfile.ZipFile(output_path, "w") as archive:\n'
            '    archive.writestr("Metadata/plate_1.gcode", "; comments only\\nG90\\n")',
            "no extrusion motion",
        ),
    ],
)
def test_zero_exit_requires_real_plate_gcode_not_merely_a_readable_zip(
    tmp_path, action, message
) -> None:
    executable = fake_bambu(tmp_path, "fake-success", action)

    with pytest.raises(InvalidSlicedArtifactError, match=message) as raised:
        validator(tmp_path, executable).validate(
            source(tmp_path), profiles=pinned_profiles(tmp_path)
        )

    result = raised.value.result
    assert result.status == BambuValidationStatus.INVALID_ARTIFACT
    assert result.return_code == 0
    assert result.artifact is None


def test_timeout_terminates_slice_and_retains_timeout_evidence(tmp_path) -> None:
    executable = fake_bambu(tmp_path, "timeout", "time.sleep(10)")
    started = time.monotonic()

    with pytest.raises(BambuStudioTimeoutError) as raised:
        validator(tmp_path, executable, timeout=0.05).validate(
            source(tmp_path), profiles=pinned_profiles(tmp_path)
        )

    result = raised.value.result
    assert result.status == BambuValidationStatus.TIMED_OUT
    assert result.timed_out
    assert not result.canceled
    assert result.return_code is not None
    assert time.monotonic() - started < 2
    assert list((tmp_path / "runs").iterdir()) == []


def test_cancel_terminates_slice_and_prelaunch_cancel_runs_no_slice(tmp_path) -> None:
    executable = fake_bambu(tmp_path, "cancel", "time.sleep(10)")
    instance = validator(tmp_path, executable)

    already_canceled = CancellationToken()
    already_canceled.cancel()
    with pytest.raises(BambuStudioCanceledError) as prelaunch:
        instance.validate(
            source(tmp_path),
            profiles=pinned_profiles(tmp_path),
            cancellation=already_canceled,
        )
    assert prelaunch.value.result.return_code is None
    assert prelaunch.value.result.command == ()
    assert not executable.with_suffix(".version-probes").exists()

    token = CancellationToken()
    timer = threading.Timer(0.05, token.cancel)
    timer.start()
    try:
        with pytest.raises(BambuStudioCanceledError) as raised:
            instance.validate(
                source(tmp_path), profiles=pinned_profiles(tmp_path), cancellation=token
            )
    finally:
        timer.cancel()
    assert raised.value.result.status == BambuValidationStatus.CANCELED
    assert raised.value.result.canceled
    assert not raised.value.result.timed_out


def test_missing_bambu_studio_is_an_actionable_unavailable_result(tmp_path) -> None:
    missing = tmp_path / "missing-bambu-studio"
    instance = validator(tmp_path, missing)

    with pytest.raises(BambuStudioUnavailableError, match="not found") as raised:
        instance.validate(source(tmp_path), profiles=pinned_profiles(tmp_path))

    result = raised.value.result
    assert result.status == BambuValidationStatus.UNAVAILABLE
    assert result.executable is None
    assert result.version is None
    assert result.return_code is None
    assert result.command == ()


def test_same_source_name_with_changed_content_cannot_reuse_slice_names(tmp_path) -> None:
    executable = fake_bambu(tmp_path, "cache-proof", VALID_SLICE)
    instance = validator(tmp_path, executable)
    first_directory = tmp_path / "first"
    second_directory = tmp_path / "second"
    first_directory.mkdir()
    second_directory.mkdir()
    first = first_directory / "same-name.3mf"
    second = second_directory / "same-name.3mf"
    with zipfile.ZipFile(first, "w") as archive:
        archive.writestr("Metadata/project_settings.config", '{"filament_settings_id":["a"]}')
        archive.writestr("proof", b"first project")
    with zipfile.ZipFile(second, "w") as archive:
        archive.writestr("Metadata/project_settings.config", '{"filament_settings_id":["a"]}')
        archive.writestr("proof", b"second project")
    profiles = pinned_profiles(tmp_path)

    first_result = instance.validate(first, profiles=profiles)
    second_result = instance.validate(second, profiles=profiles)

    assert first_result.source_sha256 != second_result.source_sha256
    assert first_result.command[-1] != second_result.command[-1]
    first_output = first_result.command[first_result.command.index("--export-3mf") + 1]
    second_output = second_result.command[second_result.command.index("--export-3mf") + 1]
    assert first_output != second_output
    assert first_result.artifact is not None
    assert second_result.artifact is not None
    assert first_result.artifact.name != second_result.artifact.name


def test_profiles_are_required_and_missing_or_changed_pins_fail_before_slice(tmp_path) -> None:
    executable = fake_bambu(tmp_path, "profiles", VALID_SLICE)
    instance = validator(tmp_path, executable)
    project = source(tmp_path)

    with pytest.raises(BambuStudioProfileError, match="requires pinned") as absent:
        instance.validate(project)
    assert absent.value.result.status == BambuValidationStatus.PROFILE_ERROR
    assert absent.value.result.command == ()

    missing = pinned_profiles(tmp_path, prefix="missing")
    missing.machine.path.unlink()
    with pytest.raises(BambuStudioProfileError, match="missing or not a file") as missing_error:
        instance.validate(project, profiles=missing)
    assert missing_error.value.result.return_code is None

    changed = pinned_profiles(tmp_path, prefix="changed")
    changed.process.path.write_text('{"type":"changed"}', encoding="utf-8")
    with pytest.raises(BambuStudioProfileError, match="fingerprint mismatch") as mismatch:
        instance.validate(project, profiles=changed)
    assert mismatch.value.result.status == BambuValidationStatus.PROFILE_ERROR
    assert mismatch.value.result.profiles[-1].role == "process"
    assert (
        mismatch.value.result.profiles[-1].expected_sha256
        != mismatch.value.result.profiles[-1].actual_sha256
    )

    wrong_role = pinned_profiles(tmp_path, prefix="wrong-role")
    wrong_role = BambuSliceProfiles(
        machine=PinnedBambuProfile.pin(wrong_role.process.path),
        process=wrong_role.process,
        filaments=wrong_role.filaments,
    )
    with pytest.raises(BambuStudioProfileError, match="machine profile declares type 'process'"):
        instance.validate(project, profiles=wrong_role)


def test_filament_profile_count_matches_extruders_and_preserves_order(tmp_path) -> None:
    executable = fake_bambu(tmp_path, "extruders", VALID_SLICE)
    instance = validator(tmp_path, executable)
    project = source(tmp_path, extruders=2)

    with pytest.raises(BambuStudioProfileError, match="expected 2, received 1"):
        instance.validate(project, profiles=pinned_profiles(tmp_path, prefix="one"))

    result = instance.validate(
        project,
        profiles=pinned_profiles(tmp_path, filaments=2, prefix="two"),
    )
    filament_argument = result.command[result.command.index("--load-filaments") + 1]
    assert filament_argument.count(";") == 1
    assert [(item.role, item.extruder) for item in result.profiles] == [
        ("machine", None),
        ("process", None),
        ("filament", 1),
        ("filament", 2),
    ]


def test_profile_bytes_participate_in_profile_and_validation_cache_fingerprints(tmp_path) -> None:
    executable = fake_bambu(tmp_path, "profile-cache", VALID_SLICE)
    instance = validator(tmp_path, executable)
    project = source(tmp_path)
    first_profiles = pinned_profiles(tmp_path, prefix="first-profiles")
    second_profiles = pinned_profiles(tmp_path, prefix="second-profiles")
    second_profiles.process.path.write_text(
        '{"type":"process","quality":"different"}', encoding="utf-8"
    )
    second_profiles = BambuSliceProfiles(
        machine=second_profiles.machine,
        process=PinnedBambuProfile.pin(second_profiles.process.path),
        filaments=second_profiles.filaments,
    )

    first = instance.validate(project, profiles=first_profiles)
    second = instance.validate(project, profiles=second_profiles)

    assert first.source_sha256 == second.source_sha256
    assert first.profile_set_sha256 != second.profile_set_sha256
    assert first.cache_key != second.cache_key


@pytest.mark.skipif(
    not os.environ.get("BAMBU_STUDIO_CLI"),
    reason="set BAMBU_STUDIO_CLI for a real generated-package sliced-G-code proof",
)
def test_installed_bambu_studio_slices_generated_package_to_verified_gcode(tmp_path) -> None:
    executable = Path(os.environ["BAMBU_STUDIO_CLI"]).expanduser().resolve()
    resources = executable.parents[1] / "Resources" / "profiles" / "BBL"
    profiles = BambuSliceProfiles(
        machine=PinnedBambuProfile.pin(resources / "machine" / "Bambu Lab P2S 0.4 nozzle.json"),
        process=PinnedBambuProfile.pin(resources / "process" / "0.20mm Standard @BBL P2S.json"),
        filaments=(
            PinnedBambuProfile.pin(resources / "filament" / "Bambu PLA Matte @BBL P2S.json"),
        ),
    )
    project = tmp_path / "generated-tetra.3mf"
    write_bambu_3mf(
        project,
        name="Generated CLI slice proof",
        meshes=(
            Mesh(
                name="Closed tetrahedron",
                vertices=((0, 0, 0), (20, 0, 0), (0, 20, 0), (0, 0, 20)),
                triangles=((0, 2, 1), (0, 1, 3), (1, 2, 3), (2, 0, 3)),
            ),
        ),
        materials=(Material("Bone White", "#CBC6B8", 1, preset="Bambu PLA Matte"),),
    )

    result = validator(tmp_path, executable, timeout=300).validate(project, profiles=profiles)

    assert result.status == BambuValidationStatus.VALIDATED
    assert result.version is not None
    assert result.artifact is not None
    assert result.artifact.gcode_members
    assert result.artifact.uncompressed_gcode_bytes > 0
    assert result.profile_set_sha256 is not None
    assert result.cache_key is not None


def test_retained_single_plate_tower_survives_profile_loading_and_enables_checks(tmp_path):
    executable = fake_bambu(tmp_path, "Bambu tower proof", VALID_SLICE)
    project = source(tmp_path, extruders=4)
    with zipfile.ZipFile(project, "w") as archive:
        archive.writestr(
            "Metadata/project_settings.config",
            json.dumps(
                {
                    "filament_settings_id": ["PLA"] * 4,
                    "wipe_tower_x": ["4"],
                    "wipe_tower_y": ["208"],
                }
            ),
        )
    result = validator(tmp_path, executable).validate(
        project, profiles=pinned_profiles(tmp_path, filaments=4)
    )
    assert "--no-check" not in result.command
    assert result.command[result.command.index("--wipe-tower-x") + 1] == "4.0"
    assert result.command[result.command.index("--wipe-tower-y") + 1] == "208.0"


@pytest.mark.parametrize(
    "coordinates", [(["nan"], ["5"]), (["4"], ["inf"]), (["4"], ["257"]), (["4", "8"], ["5"])]
)
def test_invalid_retained_tower_is_rejected_before_slice(tmp_path, coordinates):
    executable = fake_bambu(tmp_path, "Bambu invalid tower", VALID_SLICE)
    project = source(tmp_path)
    with zipfile.ZipFile(project, "w") as archive:
        archive.writestr(
            "Metadata/project_settings.config",
            json.dumps(
                {
                    "filament_settings_id": ["PLA"],
                    "wipe_tower_x": coordinates[0],
                    "wipe_tower_y": coordinates[1],
                }
            ),
        )
    with pytest.raises(BambuStudioProfileError, match="prime-tower position"):
        validator(tmp_path, executable).validate(project, profiles=pinned_profiles(tmp_path))


PREPARE_EDITABLE = r"""
import json
if "--slice" not in arguments:
    assert "--load-settings" in arguments
    assert "--load-filaments" in arguments
    with zipfile.ZipFile(output_path, "w") as archive:
        archive.writestr("3D/3dmodel.model",
            '<model><metadata name="Application">BambuStudio-02.08.02.61</metadata></model>')
        archive.writestr("Metadata/project_settings.config", json.dumps({
            "nozzle_diameter": ["0.4"], "printer_settings_id": "P2S",
            "print_settings_id": "Standard", "filament_settings_id": ["PLA"],
            "filament_colour": ["#FFFFFF"], "machine_start_gcode": "G28"
        }))
    raise SystemExit(0)
assert "--load-settings" not in arguments
assert "--load-filaments" not in arguments
assert "--filament-colour" not in arguments
assert "--no-check" not in arguments
assert Path(arguments[-1]).name == "prepared.3mf"
"""


def test_download_is_bambu_serialized_and_validated_without_profile_overlays(tmp_path):
    executable = fake_bambu(tmp_path, "prepare", PREPARE_EDITABLE + VALID_SLICE)
    input_path = source(tmp_path)
    output_path = tmp_path / "download.3mf"
    result = validator(tmp_path, executable).validate(
        input_path, profiles=pinned_profiles(tmp_path), project_output=output_path
    )
    assert result.status == BambuValidationStatus.VALIDATED
    assert output_path.read_bytes() != input_path.read_bytes()
    assert result.source_sha256 == hashlib.sha256(output_path.read_bytes()).hexdigest()
    assert "--load-settings" in result.preparation_command
    assert "--load-settings" not in result.command
    assert "--load-filaments" not in result.command
    assert "--no-check" not in result.command


@pytest.mark.parametrize("bad_application", ["Image23MF Studio 0.1", "BambuStudio-invalid"])
def test_rejects_projects_whose_config_gui_would_ignore(tmp_path, bad_application):
    action = PREPARE_EDITABLE.replace("BambuStudio-02.08.02.61", bad_application)
    executable = fake_bambu(tmp_path, "bad-import", action + VALID_SLICE)
    output_path = tmp_path / "download.3mf"
    with pytest.raises(InvalidSlicedArtifactError, match="GUI importer"):
        validator(tmp_path, executable).validate(
            source(tmp_path), profiles=pinned_profiles(tmp_path), project_output=output_path
        )
    assert not output_path.exists()


def test_prepared_project_is_not_published_when_self_contained_slice_fails(tmp_path):
    executable = fake_bambu(tmp_path, "bad-slice", PREPARE_EDITABLE + "raise SystemExit(7)")
    output_path = tmp_path / "download.3mf"
    with pytest.raises(BambuStudioSliceError):
        validator(tmp_path, executable).validate(
            source(tmp_path), profiles=pinned_profiles(tmp_path), project_output=output_path
        )
    assert not output_path.exists()


def test_preparation_failure_does_not_slice_or_publish(tmp_path):
    executable = fake_bambu(
        tmp_path, "bad-prepare", "assert '--slice' not in arguments\nraise SystemExit(7)"
    )
    output_path = tmp_path / "download.3mf"
    with pytest.raises(BambuStudioSliceError, match="preparation failed"):
        validator(tmp_path, executable).validate(
            source(tmp_path), profiles=pinned_profiles(tmp_path), project_output=output_path
        )
    assert not output_path.exists()


def test_preparation_preserves_unused_palette_slots(tmp_path):
    input_path = source(tmp_path, extruders=3)
    palette = ["#112233", "#445566", "#778899"]
    with zipfile.ZipFile(input_path, "w") as archive:
        archive.writestr(
            "Metadata/project_settings.config",
            json.dumps(
                {
                    "filament_settings_id": ["PLA"] * 3,
                    "filament_colour": palette,
                }
            ),
        )
    action = (
        PREPARE_EDITABLE.replace(
            'assert "--load-filaments" in arguments',
            'assert "--load-filaments" in arguments\n'
            '    assert arguments[arguments.index("--filament-colour") + 1] == '
            '"#112233;#445566;#778899"',
        )
        .replace('["#FFFFFF"]', repr(palette))
        .replace('["PLA"]', '["PLA"] * 3')
    )
    executable = fake_bambu(tmp_path, "unused-slot", action + VALID_SLICE)
    result = validator(tmp_path, executable).validate(
        input_path,
        profiles=pinned_profiles(tmp_path, filaments=3),
        project_output=tmp_path / "download.3mf",
    )
    assert result.status == BambuValidationStatus.VALIDATED
