"""Bounded, top-down extrusion-footprint preview of an actual Bambu slice.

This is a diagnostic rendering, not a physical print simulation. It uses the
slicer's line widths and tool colors, and never fills a region from mesh faces.
"""

from __future__ import annotations

import io
import json
import math
import re
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO, Callable
from xml.etree import ElementTree as ET

from PIL import Image, ImageDraw

CORE = "{http://schemas.microsoft.com/3dmanufacturing/core/2015/02}"
MAX_GCODE_BYTES = 256 * 1024 * 1024
MAX_LINES = 5_000_000
NUMBERS = re.compile(r"([XYZEIJR])\s*([-+]?(?:\d*\.\d+|\d+\.?\d*))")
IDENTITY = (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)


@dataclass(frozen=True)
class FootprintPreview:
    png: bytes
    artwork_mask: Image.Image
    drawn_segments: int
    width_px: int
    height_px: int


def canvas_translation(package: Path) -> tuple[float, float]:
    """Only accept the single, unrotated placement generated by our exporter."""
    with zipfile.ZipFile(package) as archive:
        root = ET.fromstring(archive.read("3D/3dmodel.model"))
    items = root.findall(f"{CORE}build/{CORE}item")
    if len(items) != 1 or root.get("unit", "millimeter") != "millimeter":
        raise ValueError("Sliced preview requires one model in millimeters")
    transform = tuple(float(v) for v in items[0].get("transform", "").split())
    if (
        len(transform) != 12
        or not all(math.isfinite(v) for v in transform)
        or transform[:9] != IDENTITY
        or abs(transform[11]) > 1e-5
    ):
        raise ValueError("Sliced preview requires the original unrotated canvas placement")
    return transform[9], transform[10]


def render_footprints(
    gcode: BinaryIO,
    *,
    palette: tuple[str, ...],
    width_mm: float,
    height_mm: float,
    origin_x: float,
    origin_y: float,
    width_px: int,
    height_px: int,
    base_top_mm: float,
    supersample: int = 3,
    check_canceled: Callable[[], None] | None = None,
) -> FootprintPreview:
    if (
        not palette
        or len(palette) > 8
        or any(not re.fullmatch(r"#[0-9a-fA-F]{6}", c) for c in palette)
        or not all(math.isfinite(v) for v in (width_mm, height_mm, origin_x, origin_y, base_top_mm))
        or min(width_mm, height_mm) <= 0
        or max(width_mm, height_mm) > 256
        or base_top_mm < 0
        or not (1 <= width_px <= 2048 and 1 <= height_px <= 2048)
        or supersample not in (1, 2, 3)
    ):
        raise ValueError("Invalid sliced preview dimensions or palette")
    # Keep physical aspect ratio; callers must not stretch a footprint to fit an image.
    if abs((width_px / height_px) / (width_mm / height_mm) - 1) > 0.01:
        raise ValueError("Sliced preview pixels must match the physical canvas aspect ratio")
    # Resolve extrusion in physical units even for a tiny source image. Without
    # this floor a 0.42 mm strand can round to 0.50 mm and hide real narrow gaps.
    density = max(width_px * supersample / width_mm, height_px * supersample / height_mm, 24)
    w, h = math.ceil(width_mm * density), math.ceil(height_mm * density)
    image = Image.new("RGBA", (w, h))
    mask = Image.new("1", (w, h))
    draw, coverage = ImageDraw.Draw(image), ImageDraw.Draw(mask)
    x = y = z = e = 0.0
    width = None
    tool = 0
    relative_e = True  # Bambu emits M83; handle M82/G92 explicitly too.
    relative_xyz = False
    byte_count = segments = 0
    for number, raw in enumerate(gcode):
        byte_count += len(raw)
        if number > MAX_LINES or byte_count > MAX_GCODE_BYTES:
            raise ValueError("Slice exceeds the preview size limit")
        if number % 4096 == 0 and check_canceled:
            check_canceled()
        line = raw.decode("ascii", errors="replace").strip()
        if line.startswith("; LINE_WIDTH:"):
            width = float(line.split(":", 1)[1])
            if not math.isfinite(width) or not 0 < width <= 5:
                raise ValueError("Unsupported extrusion width in slice")
            continue
        command = line.split(";", 1)[0].strip()
        if not command:
            continue
        op = command.split()[0]
        if op in ("G18", "G19", "G90.1"):
            raise ValueError("Unsupported arc plane or center mode in sliced preview")
        if op == "M83":
            relative_e = True
        elif op == "M82":
            relative_e = False
        elif op == "G90":
            relative_xyz = False
        elif op == "G91":
            relative_xyz = True
        elif re.fullmatch(r"T\d+", op):
            tool = int(op[1:])
        elif op in ("G0", "G1", "G2", "G3", "G92"):
            vals = {key: float(value) for key, value in NUMBERS.findall(command)}
            if not all(math.isfinite(v) for v in vals.values()):
                raise ValueError("Non-finite position in slice")
            if op == "G92":
                if any(key in vals for key in ("X", "Y", "Z")):
                    raise ValueError("Coordinate reset is unsupported in sliced preview")
                e = vals.get("E", e)
                continue
            nx = (x + vals.get("X", 0)) if relative_xyz else vals.get("X", x)
            ny = (y + vals.get("Y", 0)) if relative_xyz else vals.get("Y", y)
            nz = (z + vals.get("Z", 0)) if relative_xyz else vals.get("Z", z)
            extrusion = vals.get("E", 0) if relative_e else vals.get("E", e) - e
            e = (e + vals.get("E", 0)) if relative_e else vals.get("E", e)
            if (
                extrusion > 0
                and ("X" in vals or "Y" in vals or op in ("G2", "G3"))
                and width is not None
            ):
                positions = [(x, y), (nx, ny)]
                if op in ("G2", "G3"):
                    if "R" in vals or not any(k in vals for k in ("I", "J")):
                        raise ValueError("Only XY arcs with relative I/J centers are supported")
                    cx, cy = x + vals.get("I", 0), y + vals.get("J", 0)
                    radius_mm = math.hypot(x - cx, y - cy)
                    if radius_mm <= 0 or abs(math.hypot(nx - cx, ny - cy) - radius_mm) > 0.1:
                        raise ValueError("Invalid arc center in slice")
                    start, end = math.atan2(y - cy, x - cx), math.atan2(ny - cy, nx - cx)
                    sweep = (end - start) % math.tau if op == "G3" else -((start - end) % math.tau)
                    if abs(sweep) < 1e-10:
                        sweep = math.tau if op == "G3" else -math.tau
                    # Chord error below a quarter supersampled pixel, bounded work per arc.
                    error_mm = min(width / 20, width_mm / w / 4)
                    angle = 2 * math.acos(max(-1, 1 - min(error_mm / radius_mm, 1)))
                    steps = max(1, math.ceil(abs(sweep) / max(angle, 1e-6)))
                    if steps > 4096:
                        raise ValueError("Arc exceeds the preview complexity limit")
                    positions = [
                        (
                            cx + radius_mm * math.cos(start + sweep * i / steps),
                            cy + radius_mm * math.sin(start + sweep * i / steps),
                        )
                        for i in range(steps + 1)
                    ]
                    positions[0], positions[-1] = (x, y), (nx, ny)
                points = [
                    ((px - origin_x) / width_mm * w, (origin_y + height_mm - py) / height_mm * h)
                    for px, py in positions
                ]
                stroke = max(1, round(width / width_mm * w))
                radius = stroke / 2
                if (
                    max(p[0] for p in points) >= -radius
                    and min(p[0] for p in points) < w + radius
                    and max(p[1] for p in points) >= -radius
                    and min(p[1] for p in points) < h + radius
                ):
                    if not 0 <= tool < len(palette):
                        raise ValueError("Slice references an unknown filament on the canvas")
                    targets = [(draw, palette[tool])]
                    if nz > base_top_mm + 1e-5:
                        targets.append((coverage, 1))
                    for target, color in targets:
                        target.line(points, fill=color, width=stroke, joint="curve")
                        for px, py in (points[0], points[-1]):
                            target.ellipse(
                                (px - radius, py - radius, px + radius, py + radius), fill=color
                            )
                    segments += 1
            x, y, z = nx, ny, nz
    if not segments:
        raise ValueError("No supported model extrusion found for sliced preview")
    payload = io.BytesIO()
    image.resize((width_px, height_px), Image.Resampling.LANCZOS).save(payload, "PNG")
    return FootprintPreview(payload.getvalue(), mask, segments, width_px, height_px)


def render_sliced_preview(
    sliced: Path,
    package: Path,
    *,
    palette: tuple[str, ...],
    width_mm: float,
    height_mm: float,
    width_px: int,
    height_px: int,
    base_top_mm: float,
    check_canceled: Callable[[], None] | None = None,
) -> FootprintPreview:
    origin_x, origin_y = canvas_translation(package)
    with zipfile.ZipFile(sliced) as archive:
        settings = json.loads(archive.read("Metadata/project_settings.config"))
        if tuple(settings.get("filament_colour", ())) != palette:
            raise ValueError("Sliced preview palette differs from the exported project")
        members = [n for n in archive.namelist() if re.fullmatch(r"Metadata/plate_\d+\.gcode", n)]
        if len(members) != 1:
            raise ValueError("Sliced preview currently supports one plate")
        if archive.getinfo(members[0]).file_size > MAX_GCODE_BYTES:
            raise ValueError("Slice exceeds the preview size limit")
        with archive.open(members[0]) as gcode:
            return render_footprints(
                gcode,
                palette=palette,
                width_mm=width_mm,
                height_mm=height_mm,
                origin_x=origin_x,
                origin_y=origin_y,
                width_px=width_px,
                height_px=height_px,
                base_top_mm=base_top_mm,
                check_canceled=check_canceled,
            )
